theme: jekyll-theme-hacker

# Site settings
title: Amiga 500 USB Keyboard
description: Amiga 500 keyboard into a USB HID, allowing it to function as a modern USB keyboard. Using an Arduino Leonardo, which supports native USB communication, the sketch reads the Amiga 500 keyboard signals and translates them into USB keystrokes, preserving the vintage feel with modern compatibility.

show_downloads: true
