name: Build and Verify Sketch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install Arduino core
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr

    - name: Install Keyboard library
      run: |
        arduino-cli lib install "Keyboard"

    - name: Install CircularBuffer library
      run: |
        arduino-cli lib install "CircularBuffer"

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn arduino:avr:leonardo --warnings all --verify Amiga500-USB-Keyboard-Leonardo.ino
